version: '3.8'

services:
  # База данных нужна в обоих сценариях
  postgres:
    image: postgres:15-alpine
    container_name: vk_bot_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-vk_bot_db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Сервис бота (используется в Prod)
  bot:
    build: .
    container_name: vk_bot_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-vk_bot_db}?schema=public"
      VK_BOT_TOKEN: ${VK_BOT_TOKEN}
    # Включаем только если запускаем через docker-compose up (Prod)
    # Если нужно запустить ТОЛЬКО базу для Dev, используй: docker-compose up db

volumes:
  pgdata: